### ISSUE TITLE
第二章节图片不显示问题 的解决笔记记录

### ISSUE THREAD

**Issue by liugezhou** [QingyangKong/DynamicNFT-Tutorial#1]
在视频第二章中代码中关于 metadata 的代码。
我之前只是在 filebase 中上传了图片资源，没有上传 json文件，因此 代码中 metadata 的数据源 写的是 图片的 IPFS 地址，导致在 preMint 和mint后图片不显示。
后重新观看视频教程，关于 json 文件的上传没注意到。 
然后根据下面的json格式，将上传的图片 ipfs 地址填入，然后再上传 json文件即可。

```
{
  "description": "Desktop about Grass",
  "external_url": "https://openseacreatures.io/3",
  "image": "https://ipfs.filebase.io/ipfs/xxxxx",
  "name": "Grass",
  "attributes": [
    {
    "trait_type": "Breed",
    "value": "Grass"
    },
    {
    "trait_type": "temperature",
    "value": "average"
    }
  ]
}
```
总之就是 metadata 中的元数据引得地址应该是 json文件的ipfs地址 ，而不是 图片的 ipfs地址。
借这个 issues 做个笔记。
🫡

**Comment by QingyangKong** [comment]
好的
